# Generated by Django 6.0 on 2026-02-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_payment_refund_amount_payment_refund_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_ref',
            field=models.CharField(blank=True, help_text='Reference ID from the payment gateway', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, help_text='Raw response from the payment gateway', null=True),
        ),
    ]
