# Generated by Django 6.0 on 2026-02-12 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_payment_gateway_ref_payment_raw_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(blank=True, help_text='Wide image for hero section/backdrop (1920x600 recommended)', null=True, upload_to='movie_banners/'),
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movie_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.movie')),
            ],
        ),
    ]
